//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.AuthenticationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Connect", ReplyAction="http://tempuri.org/IUserService/ConnectResponse")]
        string Connect(string userLogin, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Connect", ReplyAction="http://tempuri.org/IUserService/ConnectResponse")]
        System.Threading.Tasks.Task<string> ConnectAsync(string userLogin, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Register", ReplyAction="http://tempuri.org/IUserService/RegisterResponse")]
        string Register(string userLogin, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Register", ReplyAction="http://tempuri.org/IUserService/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string userLogin, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsTokenStillValid", ReplyAction="http://tempuri.org/IUserService/IsTokenStillValidResponse")]
        bool IsTokenStillValid(string userLogin, string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsTokenStillValid", ReplyAction="http://tempuri.org/IUserService/IsTokenStillValidResponse")]
        System.Threading.Tasks.Task<bool> IsTokenStillValidAsync(string userLogin, string userToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Client.AuthenticationServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Client.AuthenticationServiceReference.IUserService>, Client.AuthenticationServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Connect(string userLogin, string userPassword) {
            return base.Channel.Connect(userLogin, userPassword);
        }
        
        public System.Threading.Tasks.Task<string> ConnectAsync(string userLogin, string userPassword) {
            return base.Channel.ConnectAsync(userLogin, userPassword);
        }
        
        public string Register(string userLogin, string userPassword) {
            return base.Channel.Register(userLogin, userPassword);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string userLogin, string userPassword) {
            return base.Channel.RegisterAsync(userLogin, userPassword);
        }
        
        public bool IsTokenStillValid(string userLogin, string userToken) {
            return base.Channel.IsTokenStillValid(userLogin, userToken);
        }
        
        public System.Threading.Tasks.Task<bool> IsTokenStillValidAsync(string userLogin, string userToken) {
            return base.Channel.IsTokenStillValidAsync(userLogin, userToken);
        }
    }
}
